name: My first workflow
on: 
  push:
    tags:
      - "*"
      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: whaleofatime54/randnum-workshop:${{ github.ref_name }}
      
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          text:
            "${{ secrets.SLACK_STUFF }} 
            /nRepo: ${{ github.repositoryUrl }}
            /nImageName: ${{ secrets.DOCKER_USERNAME }}/randnum-workshop:${{ github.ref_name }}
            /nImage url: https://hub.docker.com/repository/docker/${{ secrets.DOCKER_USERNAME }}/randnum-workshop"        
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
